apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
      - name: kbot
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.image.os }}-{{ .Values.image.arch }}"
        imagePullPolicy: Always
