name: CI/CD Telegram Bot

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_REGISTRY: ghcr.io
      IMAGE_REPOSITORY: andreysvirid/kbot
      OS: linux
      ARCH: amd64

    steps:
      # 1️⃣ Клонируем репозиторий вручную (как требует тест)
      - name: Checkout repository (develop branch)
        run: |
          git clone --depth 1 --branch develop https://github.com/andreysvirid/kbot_CICD.git .
          git log -1 --oneline

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Set image tag
      - name: Set image tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=v1.0.0-${SHORT_SHA}-${OS}-${ARCH}" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG"

      # 5️⃣ Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform ${{ env.OS }}/amd64 \
            -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push \
            .

      # 6️⃣ Install yq v4
      - name: Install yq v4
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # 7️⃣ Update helm/values.yaml
      - name: Update helm/values.yaml
        run: |
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" helm/values.yaml
          yq e -i ".image.os = \"${OS}\"" helm/values.yaml
          yq e -i ".image.arch = \"${ARCH}\"" helm/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push origin develop || echo "Push failed, maybe no changes"
