name: kbot

on:
  push:
    branches: [ develop ]

env:
  TARGETARCH: amd64
  TARGETOS: linux
  IMAGE_REGISTRY: ghcr.io
  IMAGE_REPOSITORY: andreysvirid/kbot

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: GHCR login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="v1.0.0-${SHORT_SHA}-${TARGETOS}-${TARGETARCH}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          docker buildx build \
            --platform ${{ env.TARGETOS }}/$TARGETARCH \
            -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${VERSION} \
            --push \
            .

      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Set version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="v1.0.0-${SHORT_SHA}-${TARGETOS}-${TARGETARCH}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Update Helm chart
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/values.yaml
          git commit -m "update version $VERSION" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git develop
